# ASSIGNMENT 1

# 1. Create a null vector of size 10 but the fifth value which is 1.

In [4]:
import numpy as np
vector=np.zeros(10)
vector[5]=1
vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

# 2. Create a vector with values ranging from 10 to 49.

In [5]:
vector1=np.arange(10,50)
vector1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
matrix=np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
array=np.array([1,2,0,0,0,4,0])

print(array)
indices=np.where(array!=0)
print("INDICES OF NON ZERO ELEMENTS ARE:",indices)

[1 2 0 0 0 4 0]
INDICES OF NON ZERO ELEMENTS ARE: (array([0, 1, 5], dtype=int64),)


# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [17]:
a=np.random.random((10,10))
print(a)

print("minimum value of 10*10 array:",a.min())
print("maximum value of 10*10 array:",a.max())

[[0.71035865 0.90431565 0.75878902 0.72120717 0.25014508 0.93285917
  0.66852696 0.20701471 0.96339319 0.01110208]
 [0.42961216 0.58452626 0.57388445 0.32721699 0.21281669 0.89543015
  0.3259413  0.52928227 0.82770021 0.57793207]
 [0.46626087 0.9175064  0.41993371 0.05826258 0.62110465 0.08008894
  0.70701428 0.336494   0.0203705  0.74182571]
 [0.28080324 0.1057585  0.06150509 0.80837257 0.83185659 0.95740299
  0.24140319 0.46912681 0.45765686 0.20237007]
 [0.11329946 0.18677862 0.08696418 0.68950789 0.54037993 0.42662925
  0.9894022  0.68654246 0.92025706 0.59174635]
 [0.11535362 0.11946886 0.52171573 0.88834291 0.81587351 0.84889353
  0.12045471 0.7568233  0.78839583 0.64255797]
 [0.64236537 0.09881309 0.3787399  0.26123186 0.46107661 0.29469451
  0.643895   0.11775366 0.47520575 0.63624865]
 [0.66919449 0.25957668 0.24979874 0.29386832 0.94194238 0.28010504
  0.65726702 0.63961784 0.18204824 0.61116672]
 [0.88553523 0.0674957  0.57901605 0.06857579 0.20534286 0.90186647
  0.98891404

# 6. Create a random vector of size 30 and find the mean value.

In [21]:
b=np.random.random(30)
print(b)
print("MEAN VALUE:",b.mean())

[0.47925901 0.13059917 0.58051206 0.20369081 0.35969291 0.29041735
 0.32317918 0.87417136 0.00528783 0.24528991 0.07268817 0.35822812
 0.8319099  0.15496706 0.25825517 0.89205154 0.01045429 0.84245353
 0.26822029 0.46699091 0.02317378 0.48794748 0.71873501 0.82522084
 0.55818225 0.02677544 0.12267548 0.85434283 0.14023713 0.78681317]
MEAN VALUE: 0.4064140662788607
